name: Update VK Live Streams

on:
  schedule:
    # Автозапуск каждые 10 минут
    - cron: '*/10 * * * *'
  workflow_dispatch: # Кнопка для ручного запуска во вкладке Actions

permissions:
  contents: write

jobs:
  update-links:
    runs-on: ubuntu-latest

    steps:
      - name: Чтение репозитория
        uses: actions/checkout@v4

      - name: Настройка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Запуск скрипта обновления
        run: node update.js

      - name: Коммит и push обновленного index.m3u8
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add disney_channel/index.m3u8
          git commit -m "Auto-update Disney Channel stream link" || exit 0
          git push
